### PR TITLE
Feature gravity effect compensation 2

### PR DESCRIPTION
**Pull request by SasaRi**
Improvement of cogging compensation algorithm:
- increased time offset at the begging of recordings
- every revolution shifted by offset value

### CODE REVIEW

**Comment by markosankovic** [comment]
Build triggered. sha1 is merged.

**Comment by markosankovic** [comment]
Build started sha1 is merged.

**Comment by markosankovic** [comment]
Build finished.

**Comment by SasaRi** [comment]
@romu4ld yes, because there's one more thing (one bug) i will need to develop and this prints and commented code will help

**Comment by markosankovic** [comment]
Build triggered. sha1 is merged.

**Comment by markosankovic** [comment]
Build started sha1 is merged.

**Comment by markosankovic** [comment]
Build finished.

**Pull request merged**
